tasks:
  - name: start
    init: pip install -r requirements.txt
    command: export FLASK_RUN_PORT=0.0.0.0
    command: export FLASK_RUN_HOST=8080
    command: export FLASK_ENV=development

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: false
